### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by Aetherum** [zecure/shadowd#14]
Hello,

I was hoping you could answer a few questions for me regarding the installation of the newer version of shadowd.

There is plenty of documentation on just installing shadowd in and of itself, I just have a few questions before I do a fresh install.

The only really relevant one is the following:
 Is there a new version for centos 7?

I didn't really want to submit an issue here but the forums are down for maintenance or were when I checked.

**Comment by zit-hb** [comment]
Hello,

now there is (shadowd-2.0.0-1.el7.centos.x86_64.rpm). I have also updated the RPM installation instructions in the documentation.

Creating issues for such questions is perfectly fine, I don't mind. The spam protection of the forum wasn't really working, so I disabled it until I find the time to write an effective protection.

Best regards,
Hendrik
