### ISSUE TITLE
how do i prepare the project with cmake 

### ISSUE THREAD

**Issue by doxsec** [zecure/shadowd#20]
i get errors when i type the following a very detail guide would help please 

# Installation
## Preparation
Use cmake to configure and prepare the project. It is a good idea to create a separate directory for this.
A typical installation might look like this.

    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Release ..

**Comment by zit-hb** [comment]
It is hard to tell without the actual error message, but you are probably missing a dependency:

* apt-get install make cmake g++
* apt-get install libssl-dev libboost-test-dev libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-regex-dev libasio-dev libcrypto++-dev libdbi-dev libdbd-pgsql libdbd-mysql

Also note that there will be no init script installed if you compile it manually, so you will have to add it to the auto start yourself. If you use the Debian package instead this is not necessary.

**Comment by doxsec** [comment]
here is the error CMake Error at CMakeLists.txt:40 (message):
  libcryptopp is missing

**Comment by zit-hb** [comment]
Yea, that is a missing dependency. It can be fixed by installing the headers, see post above.
