### ISSUE TITLE
Installation failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by Vilican** [zecure/shadowd#22]
If I try to install using .deb file, there will be an error because of nonexistant dependencies.
There is a problem with PPA too, because there's no release file.

**Comment by zit-hb** [comment]
Hey Vilican,

the Ubuntu packages are all for 14.04, that is the reason why you can not install them. At the time when I created them that was the common version. I will create some for newer versions soon though. I have started to set up a new automated build system, so it will be easier and faster to do that in the future.

For now you have to compile it yourself or use the Docker version. Both are really simple and explained on this site: https://shadowd.zecure.org/overview/shadowd/

For Ubuntu 16.04 you have to install this packages:
* apt-get install make cmake g++
* apt-get install libssl-dev libboost-test-dev libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-regex-dev libasio-dev libcrypto++-dev libdbi-dev libdbd-pgsql libdbd-mysql

Cheers,
Hendrik

**Comment by zit-hb** [comment]
One addition: if you compile it yourself there is no init file. If you want to autostart shadowd on boot you can use this systemd sevice file: https://github.com/zecure/packaging/blob/master/ubuntu/shadowd/trusty/shadowd.service

**Comment by Vilican** [comment]
Thank you, I'll try it. Closing for now.
