### ISSUE TITLE
shadowd service won't start - can't connect to database

### ISSUE THREAD

**Issue by zaphod13** [zecure/shadowd#23]
I am trying to get shadowd installed for the first time on a CentOS 7 box.  I have followed the install instructions, and modified the database section of the shadowd.ini file.  I have created the mysql database, and verified that the user and password in the ini file can connect to the new shadowd database.  Any ideas of where I am going wrong?  Below is the database config section:

```
############
# Database #
############

# Sets the libdbi database driver.
# Possible Values:
#   pgsql
#   mysql
# Default Value: pgsql
db-driver=mysql

# Sets the database host.
# Default Value: 127.0.0.1
db-host=127.0.0.1

# Sets the database port.
# Default Value: 5432
# Possible Values:
#   pgsql: 5432
#   mysql: 3306
db-port=3306

# Sets the database name.
# Default Value: shadowd
db-name=shadowd

# Sets the database user.
# Default Value: shadowd
db-user=shadowduser

# Sets the database password.
db-password=XXXXXXXXXXX

```

**Comment by zit-hb** [comment]
The config looks good to me. Do you have the package libdbi-dbd-mysql installed?

**Comment by zaphod13** [comment]
Yes I do

**Comment by zit-hb** [comment]
Alright. Did you use the socket or TCP to test the MySQL connection? Make sure to try it this way: `mysql -h127.0.0.1 -ushadowduser -pXXXXXXXXXXX shadowd`. If this does not solve the problem I will have to set up a CentOS VM to debug the problem. This will take a week though.

**Comment by zaphod13** [comment]
I was able to use the command and you suggested without any issues.  I appreciate the super quick response on this.  I am evaluating a couple of web application firewalls, so I may move on to other options.  I'll let you know if we are interested in having you pursue this further.

Thanks!
