### ISSUE TITLE
Proper packaging for Debian(8,9), CentOS\RHEL, Oracle Linux, SLES

### ISSUE THREAD

**Issue by elico** [zecure/shadowd#24]
I can try to offer my help with some of the packaging of shadowd for couple OS.
- Debian(8,9)
- Ubuntu 16.04
- CentOS\RHEL 7
- Oracle Linux 7
- SLES
- OpenSUSE Leap

**Comment by zit-hb** [comment]
Help is always appreciated. I have created the package configurations for some systems already: https://github.com/zecure/packaging

The next step is the complete automation of the build process. For Ubuntu this is already done, for other systems sadly not. Do you have experience in automating this process?

**Comment by elico** [comment]
@zit-hb I have a unique way of building and automating builds.
Take a look at one example of a build for debian:
http://gogs.ngtech.co.il/elicro/redwood-debian-deb-build

If the author will approve we can somehow integrate jenkins or travis or packager.io or openbuildservice.org or other tools\systems.
With jenkins it's pretty simple but requires a github thing which I don't remember the name of it(maybe hooks?).
Depends how often the application is being updated and if a manual build trigger is an options in the steps towards a complete automation.

**Comment by zit-hb** [comment]
I have already set up Bamboo for the .deb generation. I use Docker containers to simulate the different environments. Works really well. I would like to do the same for RPM.

Though, I have recently shifted the main focus of the documentation to a docker-compose based installation: https://shadowd.zecure.org/overview/shadowd/

Makes it so much simpler. It's good to have packages in case people prefer to set everything up manually but an auto-installer also has its merits at many times.

By any chance, are you maybe interested in finishing the Hebrew translation of the Shadow Daemon user interface? It is mostly done but in the main translation https://github.com/moomoohk/shadowd_ui/blob/dev/src/Swd/AnalyzerBundle/Resources/translations/messages.he.xlf 4 sentences are missing (they were added later), and the tooltips still have to be translated https://github.com/zecure/shadowd_ui/tree/master/src/Swd/AnalyzerBundle/Resources/tooltips.

**Comment by elico** [comment]
@zit-hb I am a bit busy these days but if you will bump this or another issue I might be able to do that.
I must warn you that Hebrew translation is one of the hardest and sometimes what seems to be a good translation for one will look terribly wrong for many others.
Can you open a dedicated issue for the hebrew translation?

**Comment by elico** [comment]
@zit-hb I didn't undestood:

> I would like to do the same for RPM.
Did you meant that you would want a Docker container that creates RPM's?
I have never used Bamboo and I really don't need it that much.
I will try to see if the packages are building for me fine manully.

**Comment by zit-hb** [comment]
> Did you meant that you would want a Docker container that creates RPM's?

Yes, exactly. To me it seems like one of the easiest solution to build for different versions of different systems. I experimented already a bit with .rpm generation through Docker but it is not really standing yet.

> I have never used Bamboo and I really don't need it that much.

The core functionality I would say it is not that different from Jenkins. Just a tool to automate the process because I don't want to generate the packages manually on every release.

> I must warn you that Hebrew translation is one of the hardest and sometimes what seems to be a good translation for one will look terribly wrong for many others.

If it works for some people I am happy already :) Hebrew also required right-to-left support but I have already done that.

> Can you open a dedicated issue for the hebrew translation?

Sounds good, I will do that in the next days.

**Comment by zit-hb** [comment]
Hey, @elico. If you are still interested, I have prepared everything at https://github.com/zecure/shadowd_ui/issues/32.

**Comment by elico** [comment]
@zit-hb it takes time and i'm not working in the next couple of weeks so I will try to a look at it later.
