### ISSUE TITLE
Python3, Flask connector, shadowd response issue.

### ISSUE THREAD

**Issue by ZuperSero** [zecure/shadowd#28]
Hope people are still active on this.
I had some parsing problems when using python3, made some small changes like changing the configparser in connector.py. Also it failed to create a proper hmac and sending the data to the daemon, after i fixed the parsing problems the daemon only respond with status code 2.
The data send to the daemon is supposed to be profile, hmac(key, jason_data) and jason_data. Something like.

`1`
`8580c17571678afd51e68e3d460c09c3abff57286ec5b169324df42deda50b19`
`{"version": "1.2.0-python", "client_ip": ..... "SERVER|HTTP_CACHE_CONTROL": "max-age=0"}}`

I tried looking through the source code for the daemon, but my C++ skills are limited. Can anyone tell me what leads the daemon to respond with `{'status': 2, 'threats': []}`
or tell me where to find the log file in the docker container?

**Comment by zit-hb** [comment]
Hey ZuperSero. I am currently not actively developing new features but I try to keep this project as maintained as I can.

There can be multiple reasons why status code 2 (STATUS_BAD_REQUEST) is returned. I recommend to turn on the logs in shadowd to get more information about the problem. You can do this by appending this snippet to `shadowd` in `docker-compose.yml`.

```
    volumes:
      - "/var/log/shadowd:/var/log/shadowd"
    command: ["/usr/bin/shadowd", "-c", "/etc/shadowd/shadowd.ini", "-U", "shadowd", "-G", "shadowd", "-L", "/var/log/shadowd/shadowd.log", "-V"]
```

You have to create the log directory with the correct permissions and restart shadowd:
```
mkdir /var/log/shadowd
chown -R 105:106 /var/log/shadowd/
./shadowdctl down
./shadowdctl up -d
```

After that you get a log file at /var/log/shadowd/shadowd.log once a request is send. It will contain an error message from this file: https://github.com/zecure/shadowd/blob/master/src/connection.cpp

**Comment by zit-hb** [comment]
Any updates on this?

**Comment by ZuperSero** [comment]
Sorry about the late answer. Thanks for the advice, it was cutting very
close to my exam. I got an A+ so everything went as it should. But sadly I
didn't have time to look at Shadowd any further. I do however have plans to
take another look at it, I'll message you if I get it all updated :)

Martin Schrøter

tir. d. 29. jan. 2019 17.52 skrev Hendrik Buchwald <notifications@github.com

**Comment by Thuong1234** [comment]
i did it like you but i recieved error when i restart shadowd.
ERROR: In file './docker-compose.yml', service 'env_file' must be a mapping not an array.
how i fix it?

**Comment by zit-hb** [comment]
> i did it like you but i recieved error when i restart shadowd.
> ERROR: In file './docker-compose.yml', service 'env_file' must be a mapping not an array.
> how i fix it?

This error means that it is not indented correctly.
