### ISSUE TITLE
Shadowd not working in my CentOs

### ISSUE THREAD

**Issue by testt23** [zecure/shadowd#31]
![Screenshot_20190825-163444](https://user-images.githubusercontent.com/3694008/63650708-547b6a80-c756-11e9-95da-9de35c67b04f.png)

I make in blacklist this rules. But not working at testing in URL: site.com/?la=../../etc/passwd

Site.com/?la=union all select 1,2,3/**/

I make host site account by cPanel and add global PHP connector for Shadowd

Path for user: /home/*user*/

**Comment by zit-hb** [comment]
First you should make sure that the PHP Connector is actually loaded. Create a PHP file with the content `<?php phpinfo();` and check the `auto_prepend_file` value. It should point to the PHP Connector. If not, make sure that it is: https://shadowd.zecure.org/overview/php_connector/

If it is properly loaded the global blacklist threshold is probably too high. 
As you can see [here](https://demo.shadowd.zecure.org/parameter/102013) and [here](https://demo.shadowd.zecure.org/parameter/102004) the impact of `../../etc/passwd` is 8 and `union all select 1,2,3/**/` is 6.

**Comment by testt23** [comment]
Hmmm, I check in my phpinfo and in line auto_prepend_file = none 

Wooww

**Comment by zit-hb** [comment]
It means the configuration file is not readable or the settings in the configuration file do not point to a working shadowd instance. It defaults to blocking all requests in that case for security reasons. You can find more information about errors here: https://shadowd.zecure.org/documentation/connectors/#problems:36331316c021a51589fe614a3f875457
