### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by lucianlazar1983** [zecure/shadowd#32]
is this project dead? I see no new commits from 2016...

**Comment by zit-hb** [comment]
It's not dead, just not under active development. The primary goals are achieved, so there is no reason to change much. I have to admit though, I would like to see the iterative learning at some point...

**Comment by lucianlazar1983** [comment]
Thank you for your quick reply, although I would like to see some development. Security and new vulnerabilities are rising extremely fast this days. Congrats anyway for the wonderful project!


-------- Original message --------
