### ISSUE TITLE
Install and configure Shadow Daemon ubuntu/CentOS plain server

### ISSUE THREAD

**Issue by fa4fahmed15** [zecure/shadowd#44]
Hello, 
I am new here, can you please guide me completely. How to install and configure Shadow Daemon ubuntu/CentOS plain server, Moreover how to add websites on it to check 

SQL injections
XML injections
Code injections
Command injections
Cross-site scripting
Local/remote file inclusions
Backdoor access

If you have proper installation how to then please provide me with details or steps etc..

**Comment by zit-hb** [comment]
Hey. You can find the installation instructions here: https://shadowd.zecure.org/overview/shadowd/

**Comment by fa4fahmed15** [comment]
@zit-hb 
how to add an application profile with the user interface to check site is under attack, sql injection  Xss etc ...
