### ISSUE TITLE
Can't get profile error

### ISSUE THREAD

**Issue by Mato-Z** [zecure/shadowd#5]
Hello,

In my finally configuration I operate shadowd and shadowd_python on one machine and database and shadowd_ui on other machine. Shadowd works ok, in apache log I see events ant it correctly connects to mysql database too. I have created profile in the shadowd_ui. But Shadowd does not get this profile... In shadowd log I see error messages: "Uncritical error Can't get profile". I tried delete and create new profiles and I drop and create whole database again... But result is still the same... Where is the problem please? 
Thanks for your help.

**Comment by OGMP-Surak** [comment]
Hi,

the most likely reason is that your *server ip* (web server) of the profile [is wrong](https://github.com/zecure/shadowd/blob/master/src/database.cpp#L103-L105). shadowd uses the id and the ip address to select a profile (for security).

If you are running shadowd on the same machine as the web server this has to be 127.0.0.1. If it is running on a different machine you have to set the ip address of that machine. If you are unsure just use netcat: `nc -vlp 9115` to start a server and `nc address 9115` to connect from the web server.

Best regards,
Hendrik

**Comment by zit-hb** [comment]
Hi,

the most likely reason is that your *server ip* (web server) of the profile [is wrong](https://github.com/zecure/shadowd/blob/v1.1.3/src/database.cpp#L103-L105). shadowd uses the id and the ip address of the client that connects to select a profile (for security).

If you are running shadowd on the same machine as the web server this has to be 127.0.0.1. If it is running on a different machine you have to set the ip address of that machine. If you are unsure just use netcat: `nc -vlp 9115` to start a server and `nc address 9115` to connect from the web server.

Best regards,
Hendrik

**Comment by Mato-Z** [comment]
@zit-hb thanks, I running shadowd and web server on a different machine I tried really all according your advices... But only IP 127.0.0.1 in profile resolved it... I hope that now operation will be without issues...

**Comment by zit-hb** [comment]
Do you redirect the shadowd port maybe? I can't think of any other reason why it should be 127.0.0.1 when it is on a different machine. If you could send me more information (like `ifconfig`) via e-mail that would help me a lot to understand the situation.

The tests you were doing in the shadowd_php issue were only done locally?

**Comment by Mato-Z** [comment]
@zit-hb If you provide me your mail contact I can send you more information...

**Comment by zit-hb** [comment]
I did not include it, because it is displayed on the Github page and the home page, but here it is again: `contact@zecure.org`
