### ISSUE TITLE
bad request error from shadowd

### ISSUE THREAD

**Issue by illegalprime** [zecure/shadowd#50]
hello!

I followed the getting started guide: https://shadowd.zecure.org/overview/shadowd/
and installed shadowd with docker-compose and connected it to my django app via the middleware.
since I'm still running on Python 2 I'm using the 2.0.0 version of the python connector

it seems like requests are coming in but I don't see any in the UI, the verbose logs show:
```
shadowd_1  | 2021-02-09 20:40:10        Warning Bad request from 172.19.0.1
shadowd_1  | 2021-02-09 20:40:15        Notice  Starting new connection with 172.19.0.1
```

the python connector also has these errors:
```
Exception: bad request
2021-02-09 15:48:27     Traceback (most recent call last):
  File "/home/ubuntu/venv-app/lib/python2.7/site-packages/shadowd/connector.py", line 267, in start
    config.get('ssl')
  File "/home/ubuntu/venv-app/lib/python2.7/site-packages/shadowd/connector.py", line 208, in send
    return self.parse_output(output)
  File "/home/ubuntu/venv-app/lib/python2.7/site-packages/shadowd/connector.py", line 218, in parse_output
    raise Exception('bad request')
```

I read the source code of the connector and found that it was sending a request to be processed by shadowd and then reading the bad_request status from the shadowd server, so I don't think this is a connector issue.

I modified the connector source to print what payload it was sending and I got (EC2 ELB health checks):
```JSON
{
  "client_ip": "127.0.0.1",
  "resource": "/status/check",
  "caller": "/status/check",
  "version": "2.0.0-python",
  "input": {
    "SERVER|HTTP_HOST": "X.X.172.140",
    "SERVER|HTTP_ACCEPT": "*/*",
    "SERVER|HTTP_X_REAL_IP": "X.X.184.142",
    "SERVER|HTTP_USER_AGENT": "ELB-HealthChecker/1.0",
    "SERVER|HTTP_X_FORWARDED_FOR": "X.X.184.142"
  },
  "hashes": {}
}
```

here is my connector config:
```
$ grep -v \; /etc/shadowd/connectors.ini 
[shadowd_python]
profile=default

key=SOME_SECRET_KEY

observe=1

debug=1

log=/var/log/django/shadowd.log
```

I set up a profile in the UI as per the Getting Started instructions:
![Screenshot_20210209_155256](https://user-images.githubusercontent.com/4401220/107426996-e9128d80-6aee-11eb-887b-8e5422892b7e.png)

I'm using these tags in docker-compose: `zecure/shadowd:2`, `zecure/shadowd_ui:2`, `zecure/shadowd_database:12.4`.

I feel like I'm probably missing something very small, do you know how to debug this issue further?

**Comment by zit-hb** [comment]
Hello Michael! That is strange, the error implies that [consume()](https://github.com/zecure/shadowd/blob/master/src/request_parser.cpp#L40-L72) returns `false`. That is not something I have encountered before. Could you add a debug print [here](https://github.com/zecure/shadowd_python/blob/v2.0.0/shadowd/connector.py#L192) and tell me what it sends? Thanks!

**Comment by zit-hb** [comment]
Ah, I see it now. No need to add the print. `profile` is supposed to be an integer, the profile id. It is a string in your case, so the parser fails. It should be `1`.

**Comment by zit-hb** [comment]
There hasn't been any activity for a month and the problem should be solved, so I am going ahead and close this issue.
