### ISSUE TITLE
Getting "500 Internal Server Error" after installing - PHP Connector

### ISSUE THREAD

**Issue by alonf1983** [zecure/shadowd#52]
Hi.
 i would appriciate your help.

1) i have install the Shadow Daemon and setup a profile
2) i have added: auto_prepend_file  "/usr/share/shadowd/php/Connector.php" 
(already checked that it's works by test.php insated of Connector
3) i created the folder: /etc/shadowd/ and cp the connectors.ini after modify the profile and key.

from this point i get in my site ""500 Internal Server Error"

the apache error log contain:
[Wed Mar 10 07:49:09.485679 2021] [:error] [pid 17849] [client XXXX:1884] PHP Fatal error:  Uncaught Error: Call to undefined function shadowd\\mb_check_encoding() in /usr/share/shadowd/php/Input.php:141\nStack trace:\n#0 /usr/share/shadowd/php/Input.php(137): shadowd\\Input->flatten('uvv7n0om7oequln...', 'PHPSESSID', 'COOKIE')\n#1 /usr/share/shadowd/php/Input.php(137): shadowd\\Input->flatten(Array, 'COOKIE', false)\n#2 /usr/share/shadowd/php/Input.php(104): shadowd\\Input->flatten(Array)\n#3 /usr/share/shadowd/php/Connection.php(75): shadowd\\Input->getInput()\n#4 /usr/share/shadowd/php/Connector.php(53): shadowd\\Connection->send(Object(shadowd\\Input))\n#5 /usr/share/shadowd/php/Connector.php(100): shadowd\\Connector::start()\n#6 {main}\n  thrown in /usr/share/shadowd/php/Input.php on line 141

Could you guide me please?

Thanks

**Comment by JulienBaltha** [comment]
Hi ! I'm getting the same error, what caused it ?
