### ISSUE TITLE
issues in Active Mode

### ISSUE THREAD

**Issue by alonf1983** [zecure/shadowd#54]
Hi.
i would appriciate your help.

1) i have install the Shadow Daemon and setup a profile
2) i have added: auto_prepend_file "/usr/share/shadowd/php/Connector.php"
(already checked that it's works by test.php insated of Connector

![image](https://user-images.githubusercontent.com/33452418/110693581-46822300-81f0-11eb-94c5-b7664750e408.png)

3)i created the folder: /etc/shadowd/ and cp the connectors.ini after modify the profile and key.

![image](https://user-images.githubusercontent.com/33452418/110693835-91039f80-81f0-11eb-9f26-50d832dde3f8.png)

however no requests in the Shadow Daemon User Interface

there is no errors in apache2\error.log

i have enabled the debug mode in the connector but i dont see any logs

could you guide me how to find the issue?

Thanks

**Comment by alonf1983** [comment]
-UPDATE-

in "LEARNING" mode its works good
in "ACTIVE" mode its not see the request

do you know why??

**Comment by zit-hb** [comment]
The request is only logged in "active" mode when it is malicious. You only have the blacklist enabled, so the impact of a parameter must be above a threshold. See [here](https://shadowd.zecure.org/documentation/blacklist/) and #53.

**Comment by zit-hb** [comment]
There hasn't been any activity in over a month, so I am going ahead and closing this issue.
