### ISSUE TITLE
Can't manage to whitelist numerical IP host header

### ISSUE THREAD

**Issue by Yeeheet** [zecure/shadowd#55]
Hi,

I'm currently trying your WAF and keep getting this message :

![image](https://user-images.githubusercontent.com/22061011/112489171-7ac41a80-8d7e-11eb-8973-34537bb82280.png)

I made a whitelist rule as mentionned in your documentation but no luck : 

![image](https://user-images.githubusercontent.com/22061011/112489517-cc6ca500-8d7e-11eb-9331-4af3caa9c23d.png)

I also just got this one that keeps appearing and that I don't quite understand : 

![image](https://user-images.githubusercontent.com/22061011/112489309-9deeca00-8d7e-11eb-9306-191e59931ef7.png)

I'm also blocked from accessing instructions.php and phpinfo.php from DVWA. Any idea why ?

One more thing, I generated rules from the generator page and now if I set my profile to blocking I just can't access the app. It tells me that shadowd blocked a critical attack but in passive/learning it's all good.

Thanks for your help !

**Comment by zit-hb** [comment]
Hey,

the log messages seem to be from mod_security, so not related to shadowd. `Numeric` means the host can only consist of numbers but if it is an IP address there are also dots in there. Try `Numeric (Extended)` instead. You can find the included characters here: https://shadowd.zecure.org/documentation/whitelist/

If the request is blocked in "active" mode it should be logged. So you can simply go to "Analysis", "Parameters" and you should see what parameter causes the problem (just look out for red boxes there). If you click on the magnifying glass on the right side you can see even more details.

**Comment by Yeeheet** [comment]
Hi,

Thanks for your response !

I'm gonna try that.

You mean the unkown tag ? I've got many requests with the tag.

I've also created a rule to allow all headers but it didn't change anything that's why I created one just to see if it'd work.

**Comment by Yeeheet** [comment]
I've put the whitelist rule in numeric extended but I still get the message.

When I put the profile in active mode I get the internal server error that makes DVWA unusable, wonder why.

**Comment by zit-hb** [comment]
Have you checked the "parameters" page? If you could share a screenshot of that I could tell you more easily why the request is blocked. It could be for example because of the integrity check, i.e. there is no checksum for the script that you are trying to execute.

**Comment by zit-hb** [comment]
Here are some examples:

   * no whitelist rule for the parameter: https://demo.shadowd.zecure.org/parameter/561481
   * violated whitelist rule: https://demo.shadowd.zecure.org/parameter/561490
   * no or violated integrity rule: https://demo.shadowd.zecure.org/parameters?parameter_filter%5BincludeRequestIds%5D%5B%5D=66943

**Comment by Yeeheet** [comment]
Hey !

Here is the parameter page screen : 

![image](https://user-images.githubusercontent.com/22061011/112801353-156b7480-9071-11eb-9bb3-b00d3b67ba97.png)

It is weird that it says no match while in extended, maybe the other rule for "SERVER|HTTP_*" I setup is overlapping ?

I indeed haven't created an intergrity check for these pages.  Okay so if I got it right the "unkown" tag is because I've got no integrity checks right ? How do I set it up ? Is it the digest of the parameters ?

Also, I used to get error 500 now it's just forbidden. Here is the log :

![image](https://user-images.githubusercontent.com/22061011/112802302-4f894600-9072-11eb-8206-1abc0e812d6e.png)


Thanks for your help !

**Comment by zit-hb** [comment]
Hey!

1. My bad, the regular expression is actually `^-?(?:\d+|\d*(\.|,)\d+)$`, so that is why it did not match. Only "[Special Characters](https://github.com/zecure/shadowd/blob/v2.0.2/misc/databases/pgsql_layout.sql#L570)" (and "Everything" of course) would match.
2. Yes, the "unknown" means that there is no matching integrity rule. It is the digest of the file that is executed. You can generate that with the rules generator as well or disable the integrity check for now. You can find more information [here](https://shadowd.zecure.org/documentation/integrity/).
3. "Forbidden" does not come from shadowd, it only produces the "[Internal Server Error](https://github.com/zecure/shadowd_php/blob/v2.0.2/src/Output.php#L29)".

**Comment by Yeeheet** [comment]
Thanks for your help I've setup shadowd correctly it's now in a good state !

The only thing now is that my connection gets reset instead of the 500 error. The forbidden error comes from modsecurity I found.

**Comment by zit-hb** [comment]
Great, I am glad I could help!

Looking at your previous image I would say the "Forbidden" comes from mod_security: "Access denied with code 403 (phase 4). Operator GE matched 4 at TX:outbound_anomaly_score."

**Comment by Yeeheet** [comment]
I only get that 403 page never the 500 error but everything is working so no problem.

Thanks again !
