### ISSUE TITLE
bad requests from apache2

### ISSUE THREAD

**Issue by Thuong1234** [zecure/shadowd#60]
i used php Connector to connect webserver with shadowd on other machine.  when it run i recieve errors like below.
![Screenshot (579)](https://user-images.githubusercontent.com/41165321/116022210-f19d4d80-a673-11eb-8a26-951c8c36b501.png)

**Comment by zit-hb** [comment]
Hey, you are missing `php-mbstring`. The current dev version of shadowd_php already has a polyfill for that, I will release it in the next few weeks.

**Comment by Thuong1234** [comment]
how i fixing it now? i try to install php-mbstring but it unable on kali.

**Comment by Thuong1234** [comment]
i installed php-mbstring already but it not run. How i fixing it now?

**Comment by zit-hb** [comment]
Have you restarted Apache afterwards? That is necessary to load new PHP modules.

**Comment by Thuong1234** [comment]
i connected webserver with shadowd by php connector already, when i set up shadowd like reverse proxy with nginx, i can't connect nginx with shadowd. i get some error. 
![Screenshot (613)](https://user-images.githubusercontent.com/41165321/117605577-4071d980-b182-11eb-8cae-5108830e3fad.png)
