### ISSUE TITLE
Question of installation

### ISSUE THREAD

**Issue by L3V14TH4N** [zecure/shadowd#7]
well, considering that many users have no experience with infrastructure, I wanted to know if they could create a video teaching how to install the waf (shadowd)? it would be interesting, especially in the tutorial system CentOS.

**Comment by zit-hb** [comment]
Hey, I have started working on a new version of Shadow Daemon that I want to release early next year. It will mainly introduce improvements to make the installation and usage easier. I will create videos and better tutorials once this update is released :)

**Comment by L3V14TH4N** [comment]
Nice, that's very good!! I am using here in my business the NAXSI, however, as it has no graphical interface, which is very bad for my boss. I have been testing the shadowd here and hope to continue with it. Thanks!!!

**Comment by zit-hb** [comment]
Sounds interesting. I agree, a good interface can help a lot to create more secure rules and better understand attacks. At the moment the main problem of Shadow Daemon is the amount of work required to use the whitelist. But I know how to fix this problem. The next version will also include some nice graphs and charts with representations of attacks.

**Comment by L3V14TH4N** [comment]
Hi
could send me the configuration files from both servers, since MASTER well as SLAVE.?? I can only install with docker without it works not

**Comment by zit-hb** [comment]
The configuration files depend on your environment, so I can't send you premade files. There is not much you have to change in the default configs though. In the shadowd.ini mainly the database settings and in the connectors.ini the profile id and key. But you need the connectors.ini for the Docker version too, so all that is different is the shadowd.ini.
