### ISSUE TITLE
Processing Exception (PHP Connector)

### ISSUE THREAD

**Issue by coutDeadendl** [zecure/shadowd#70]
Running on CentOS 7, Apache/2.4.6 (CentOS), PHP 7.3.29.

Loading my site shows nothing, not even an error page.

Apache error log says this:

> [Sat Aug 14 17:14:20.484411 2021] [php7:notice] [pid 85387] [client 192.168.234.129:57526] shadowd: shadowd\\Exceptions\\ProcessingException: #0 /usr/share/shadowd/src/Connection.php(90): shadowd\\Connection->parseOutputData('')\n#1 /usr/share/shadowd/src/Connector.php(55): shadowd\\Connection->send(Object(shadowd\\Input))\n#2 /usr/share/shadowd/shadowd.php(26): shadowd\\Connector->start()\n#3 {main}

Shadowd's user interface via localhost (127.0.0.1) is working just fine.

**Comment by zit-hb** [comment]
It likely means that the host or port that you have specified in the connector config is not correct. Can you tell me what value you are using there?

It seems you are using shadowd_php 2.1.0. This version should display a nice error page explaining the problem. Is `templates` disabled in your connector config by any chance?

**Comment by coutDeadendl** [comment]
I'm using 127.0.0.1:8080; templates is enabled and properly displays on different errors.

**Comment by zit-hb** [comment]
On port 8080 is the user interface. The shadowd instance is listening on port 9115 by default, so that is the port you have to connect to in the connector.

**Comment by coutDeadendl** [comment]
That was the exact issue, thank you so much.
