### ISSUE TITLE
Issue on installing

### ISSUE THREAD

**Issue by killmasta93** [zecure/shadowd#77]
Hi,
Currently i was wondering if someone could shed some light,
Currently installed shadowd on ubuntu 20.04LTS server. The webGUI is working fine and created a profile by default.
I also installed nginx on the server to put basic website, testing it with the default of the nginx without SSL for now
After i created the basic profile on the WebGUI on the same server i downloaded shadowd_php-2.1.1.tar.gz
unzip and moved it to 
```
root@test2:~# ls -l -h /usr/share/shadowd/
total 128K
-rw-rw-r-- 1 test2 test2  15K Oct 16 06:40 LICENSE
-rw-rw-r-- 1 test2 test2 1.6K Oct 16 06:40 README.md
-rw-rw-r-- 1 test2 test2  407 Oct 16 06:40 composer.json
-rw-rw-r-- 1 test2 test2  71K Oct 16 06:40 composer.lock
drwxrwxr-x 2 test2 test2 4.0K Oct 16 06:40 inc
drwxrwxr-x 4 test2 test2 4.0K Oct 16 06:40 misc
-rw-rw-r-- 1 test2 test2   53 Oct 16 06:40 phpunit.xml
-rw-rw-r-- 1 test2 test2  872 Oct 16 06:40 shadowd.php
drwxrwxr-x 3 test2 test2 4.0K Oct 16 06:40 src
drwxrwxr-x 2 test2 test2 4.0K Oct 16 06:40 tests
drwxrwxr-x 2 test2 test2 4.0K Oct 16 06:40 tpl
drwxrwxr-x 4 test2 test2 4.0K Oct 16 06:45 vendor
```
then on my nginx config this is what i have

```
# Default server configuration
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
	        # proxy_pass http://localhost:8080;
        	# proxy_http_version 1.1;
	        # proxy_set_header Upgrade $http_upgrade;
        	# proxy_set_header Connection 'upgrade';
	        # proxy_set_header Host $host;
        	# proxy_cache_bypass $http_upgrade;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
 location ~ \.php$ {
         include snippets/fastcgi-php.conf;
         fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         include fastcgi_params;
fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/shadowd.php";
    }
}

```
Then created a folder to pass the connectors
```

root@test2:~# ls -l -h /etc/shadowd/
total 4.0K
-rw-r--r-- 1 root root 2.1K Jan 25 23:11 connectors.ini

```
then i go to the rules generator but it does not generate the rules

this is my connector.ini

```
root@test2:~# cat /etc/shadowd/connectors.ini
[shadowd_php]
; Sets the profile id. Required.
profile=2

; Sets the key for the profile. Required.
key=mypassword

; Sets the address of the shadowd server.
; Default Value: 127.0.0.1
host=127.0.0.1

; Sets the port of the shadowd server.
; Default Value: 9115
;port=

; Sets the connection timeout (in seconds).
; Default Value: 5
;timeout=

; Sets the path to the public key and enables SSL. It requires enabled SSL in
; shadowd, otherwise the connection will fail.
;ssl=

; If activated threats are not removed. This can be used to test new rules without
; making the web application unusable. It can be also used to turn Shadow Daemon
; into a high-interaction web honeypot.
; Possible Values:
;   0
;   1
; Default Value: 0
;observe=

; If activated the templating system will print proper error messages instead of a
; generic error.
; Possible Values:
;   0
;   1
; Default Value: 1
;templates=

; If activated log messages are send to the web server and saved in the log file.
; Additionally, stack traces for exceptions are shown in the templates.
; Possible Values:
;   0
;   1
; Default Value: 0
debug=1

; If set the ignore list is used to ignore certain parameters and not send them to
; the shadowd server. It is good practise to not send passwords or other very
; sensitive information to the server.
;ignore=

; If activated raw post data is saved as user input. The raw data is hard to analyze,
; but can be a source for malicious input as well.
; Possible Values:
;   0
;   1
; Default Value: 0
;raw_data=

; Sets the source for the client ip. It is a key of $_SERVER. If you are using a
; reverse proxy or something similar forward the real client ip and reference it
; here, e.g., HTTP_X_FORWARDED_FOR.
; Default Value: REMOTE_ADDR
;client_ip=

; Sets the source for the caller. It is a key of $_SERVER. If you are using web
; application with a front controller or something like that change it to PHP_SELF.
; Default Value: SCRIPT_FILENAME
;caller=

; Sets the source for the resource identifier. It is a key of $_SERVER.
; Default Value: REQUEST_URI
;resource=

```

Thank you

**Comment by zit-hb** [comment]
Hi @killmasta93 ,

To use the generator you first have to capture requests in the "learning mode". This mode does nothing else but to store every request, no matter if it is an attack or not. This also means it can cause a lot of database load, so be very careful when enabling this on a production system.

You can find more details on this page: https://shadowd.zecure.org/tutorials/rules/

**Comment by killmasta93** [comment]
Thank you so much for the reply, whats odd is that i do not see any capture requests currently testing it on my test server
not sure if i missed a step, already configured the connector though php on my NGINX

**Comment by zit-hb** [comment]
My pleasure! Try creating a file with `<php phpinfo();` in it and open it up. There you can see if the connector shows up in the setting `auto_prepend_file`. If it does, you know it is loaded.

**Comment by zit-hb** [comment]
If it does not show up, make sure to both reload `nginx` and `php-fpm`.

**Comment by killmasta93** [comment]
Thanks for the reply this is the error im getting

![image](https://user-images.githubusercontent.com/13953629/151275903-39e054eb-96a2-4306-88b7-3c0bf7d5ae58.png)

**Comment by zit-hb** [comment]
The error message is "Can't get profile". It means there is no profile with the id 2 (that's the one specified in your connector config). Did you create a profile first in the admin panel? Or is the id maybe 1?

**Comment by killmasta93** [comment]
Thank you for the reply im attaching the photo

![image](https://user-images.githubusercontent.com/13953629/151482530-e03eb918-2188-4dca-97fa-bf0e55cd50ff.png)

**Comment by zit-hb** [comment]
Okay, what I said before was not right. The error message means either that the profile does not exist **or** that the "Server IP" value is not correct. The "Server IP" restricts which connector can connect to shadowd. So it is an additional limitation together with the key of the profile. Unfortunately, it is not possible to use this with the Docker version of shadowd since shadowd receives a Docker IP address and not the one from the actual connector. So this value here should be `*` (as explained [here](https://shadowd.zecure.org/overview/user_interface/), the bold "important").

**Comment by killmasta93** [comment]
Thanks for the reply, so i deleted the profile and left it like this, currently this is my phpinfo
So if i understood correctly, i leave this profile for many websites that i have aslong as i insert the php?

`fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/shadowd.php";`

![image](https://user-images.githubusercontent.com/13953629/151678343-3913e3ad-a44d-4ec7-89cb-fd9d3ca11ff0.png)

![image](https://user-images.githubusercontent.com/13953629/151678372-d150ea9a-b8b4-42dc-95c9-cca6f2b760b4.png)

**Comment by zit-hb** [comment]
Sorry for the late response, missed your question. If I understand you correctly you are asking if you should use one profile for multiple sites? It is possible but in general I would not recommend it. Usually, I create one profile for each vhost.
