### ISSUE TITLE
Connector setup with Apache web server

### ISSUE THREAD

**Issue by jxrrelo** [zecure/shadowd#82]
I am referring to the documentation and have set up the Docker containers. Both the UI and servers are up, however the server is returning {"message":"Bad request from 172.19.0.1","status":2,"threats":[]}. It is likely due to the auto_prepend_file which I have not configured because I am unsure where to add it to. May I know where am I supposed to add the following line to?

`php_value  auto_prepend_file  "/usr/share/shadowd/php/shadowd.php"`

Thanks.

**Comment by zit-hb** [comment]
It makes most sense to include it in the [<VirtualHost>](https://httpd.apache.org/docs/2.4/vhosts/examples.html) that you want to protect. You could also use a [.htaccess](https://github.com/zecure/shadowd_php/blob/master/misc/examples/.htaccess) file.

For more details see here: https://www.php.net/manual/en/configuration.changes.php
