### ISSUE TITLE
SSL mode database connection

### ISSUE THREAD

**Issue by PaoloC68** [zecure/shadowd#92]
Is there any to enable the SSL mode for the postgresql database, done as `sslmode=require` in the connection string?

**Comment by zit-hb** [comment]
Hey @PaoloC68, shadowd is not using a connection string. This are the options that the database driver supports: https://libdbi-drivers.sourceforge.net/docs/dbd_pgsql/options.html

SSL/TLS is not mentioned anywhere, so I am afraid it is not something that the database driver supports.
