### ISSUE TITLE
Docker allows external access to 9115

### ISSUE THREAD

**Issue by jorgedferreira** [zecure/shadowd#93]
Hi, good morning. Apparently Docker issues commands to iptables to allow the ports from outside the server.

Event with configuration to listen only on 127.0.0.1 i was able to connect from external server.

Is this a possible security concern?

**Comment by zit-hb** [comment]
Good morning,

I would not make it publicly accessible, even if an attacker can't do anything without a correct password.

To bind it to localhost you have to change [this line](https://github.com/zecure/shadowdctl/blob/v2.0.0/docker-compose.yml#L29) to `127.0.0.1:9115:9115` and then restart Shadow Daemon.

**Comment by jorgedferreira** [comment]
Hi. I've changed the seeings in the yaml and shadowd.ini and the connectors, but when i change the port it stops working. 

`telnet 127.0.0.1 9919
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.`

I've since changed back to 9115 with the restriction to 127.0.0.1 and it works.

**Comment by zit-hb** [comment]
I would need the contents of the configuration files to understand why the problem with the port happened. I guess somewhere the mapping was just not correct. But I guess if it is working now, that won't be necessary anymore :+1:

**Comment by jorgedferreira** [comment]
The original docker yaml settings allow for remote communication with the container from outside the server. Maybe the default should be binding to 127.0.0.1 as referred above.

**Comment by zit-hb** [comment]
Good point, I created a [ticket](https://github.com/zecure/shadowdctl/issues/2).
