### ISSUE TITLE
Shadowd identified valid HTML content as xss and sqli

### ISSUE THREAD

**Issue by jorgedferreira** [zecure/shadowd#94]
Hi, hope you are well.

I have a CMS where some fields are edited with CKEditor. Content sent to PHP is valid HTML but even so i get this:

`Blacklist: Matching Filters

Filter ID | Impact | Classification | Description
-- | -- | -- | --
5 | 3 | xss | HTML breaking
10 | 3 | xss | Unquoted HTML breaking with closing tag
101 | 2 | sqli | Common SQL function "version"
108 | 2 | sqli | Common SQL comparison "where"
111 | 3 | sqli | Common SQL comparison "where"
`

It is a product description, so where and version are actually normal words. There is no invalid HTML or xss...
Is there a way of whitelisting a sub directory? the CMS panel is in a folder, like https://example.com/manager/* 

Thanks, and best regards,

**Comment by zit-hb** [comment]
Hey Jorge,

Sure, that is no problem. You can use `*` as a wildcard for both caller and path. So you create a custom blacklist rule with the threshold `-1` for a caller `/var/www/manager/*` or whatever the path is in your case. Let me know if there are any questions!
