### ISSUE TITLE
Can Shadow Shadow Daemon connector work with windows server

### ISSUE THREAD

**Issue by Lamis-H** [zecure/shadowd#95]
Hi, Hope you are doing great...

I'm running the Shadow Daemon in Linux server "Redhat" and one of my application hosted in windows server . I need to implement the connector to the windows server, is it possible ? if it's possible kindly I need the documentation on how to configure the connector. 

Thanks. 

Best regards...

**Comment by zit-hb** [comment]
Hi Lamis,

I have never tested it with Windows myself but there is nothing operating system specific about the connector except the default path for the configuration. So if you modify the configuration path it should work fine. You can modify the configuration file with the environment variable `SHADOWD_CONNECTOR_CONFIG`.
